FROM php:7.4-apache

# Copie des fichiers du site
COPY src/ /var/www/html/

# Variables d'environnement pour le nom d'utilisateur, le mot de passe, et les adresses IP
ENV USERNAME=pc-01
ENV PASSWORD=YeOa8d03jxP
ENV IP_PC01=192.168.10.4
ENV IP_HACKER=192.168.10.2

# Expose le port 80
EXPOSE 80
